server:
  port: 21288
virtuoso:
  url: "jdbc:virtuoso://localhost:1111/charset=UTF-8/log_enable=2"
#  url: "jdbc:virtuoso://db:1111/charset=UTF-8/log_enable=2"
  usr: "dba"
  psw: "dba"
#  graph: "https://webids/"
shacl:
  url: "https://raw.githubusercontent.com/dbpedia/wall-of-fame/master/src/main/resources/shacl/shapes.ttl"
log:
  file: "./errorLog.jsonld"
github:
  client_id: "4b7a8dc331564a418882"
spring:
  main:
    banner-mode: "log"


